from dataclasses import dataclass


@dataclass
class MethodologyDefinition:
    title: str
    category: str       # "Descriptive"|"Regression"|"Clustering"|"Time Series"|
                        # "Dimensionality"|"Anomaly"|"Survival"|"Association"|"Business"
    overview: str
    when_to_use: str
    steps: list[str]
    assumptions: list[str]
    libraries_used: list[str]
    min_rows: int


METHODOLOGY_REGISTRY: dict[str, MethodologyDefinition] = {
    "descriptive_stats": MethodologyDefinition(
        title="Descriptive Statistics", category="Descriptive",
        overview="Summarizes central tendency, spread, and distribution of numeric columns.",
        when_to_use="Always a good starting point before any other analysis.",
        steps=["Compute mean/median/mode", "Compute std/variance/IQR/skewness/kurtosis",
               "Count missing and unique values", "Frequency counts for categorical columns",
               "Generate histograms + bar charts"],
        assumptions=["No specific assumptions required"],
        libraries_used=["pandas", "scipy.stats"], min_rows=1,
    ),
    "correlation": MethodologyDefinition(
        title="Correlation Analysis", category="Descriptive",
        overview="Measures linear relationships between numeric columns.",
        when_to_use="Use to identify which variables move together.",
        steps=["Compute Pearson correlation matrix", "Compute Spearman correlation matrix",
               "Identify top correlated pairs", "Generate heatmap + top-pairs chart"],
        assumptions=["Pearson assumes linearity; Spearman is non-parametric"],
        libraries_used=["pandas", "scipy.stats"], min_rows=10,
    ),
    "ttest": MethodologyDefinition(
        title="T-Test", category="Descriptive",
        overview="Tests whether means of two groups are significantly different.",
        when_to_use="Use when comparing a numeric metric between two groups.",
        steps=["Auto-detect test type (one-sample/independent/paired)",
               "Shapiro-Wilk normality test", "Levene equal-variance test",
               "Run t-test", "Report t-stat, p-value, CI, Cohen's d"],
        assumptions=["Approximately normal within groups", "Independent groups"],
        libraries_used=["scipy.stats"], min_rows=10,
    ),
    "anova": MethodologyDefinition(
        title="ANOVA", category="Descriptive",
        overview="Tests whether means differ across 3+ groups.",
        when_to_use="Use when comparing a numeric metric across 3 or more categories.",
        steps=["One-way ANOVA F-statistic and p-value",
               "Tukey HSD post-hoc if significant", "Report eta-squared effect size",
               "Generate box plots per group"],
        assumptions=["Normality within groups", "Homogeneity of variances"],
        libraries_used=["scipy.stats", "statsmodels"], min_rows=20,
    ),
    "chi_square": MethodologyDefinition(
        title="Chi-Square Test", category="Descriptive",
        overview="Tests whether two categorical variables are independent.",
        when_to_use="Use when both variables are categorical.",
        steps=["Build contingency table", "Compute expected frequencies",
               "Chi-square stat and p-value", "Cramer's V effect size",
               "Generate contingency heatmap"],
        assumptions=["Expected frequency >= 5 per cell", "Independent observations"],
        libraries_used=["scipy.stats"], min_rows=20,
    ),
    "mann_whitney": MethodologyDefinition(
        title="Mann-Whitney U Test", category="Descriptive",
        overview="Non-parametric alternative to T-Test. Compares two groups without normality assumption.",
        when_to_use="Use instead of T-Test when data is not normally distributed.",
        steps=["Rank all observations", "Compute U-statistic and p-value",
               "Rank-biserial correlation effect size", "Generate box plots + density plot"],
        assumptions=["Independent observations", "Ordinal or continuous data"],
        libraries_used=["scipy.stats"], min_rows=10,
    ),
    "regression_linear": MethodologyDefinition(
        title="Linear Regression", category="Regression",
        overview="Models the linear relationship between a target and predictor variables.",
        when_to_use="Use to predict a continuous value or understand predictor effects.",
        steps=["Select target and features", "80/20 train-test split",
               "Fit OLS regression", "Report R2, RMSE, MAE, coefficients with p-values",
               "Generate actual vs predicted scatter + residual plot"],
        assumptions=["Linear relationship", "Homoscedasticity", "Normal residuals"],
        libraries_used=["scikit-learn", "statsmodels"], min_rows=30,
    ),
    "regression_logistic": MethodologyDefinition(
        title="Logistic Regression", category="Regression",
        overview="Predicts probability of a binary outcome.",
        when_to_use="Use when target has two categories (yes/no, churn/retain).",
        steps=["Select binary target and features", "80/20 split",
               "Fit logistic regression", "Report accuracy, precision, recall, F1, AUC-ROC",
               "Generate ROC curve + confusion matrix"],
        assumptions=["Binary outcome", "Independent observations"],
        libraries_used=["scikit-learn"], min_rows=50,
    ),
    "regression_polynomial": MethodologyDefinition(
        title="Polynomial Regression", category="Regression",
        overview="Fits a curved relationship between a single predictor and target.",
        when_to_use="Use when the relationship is clearly curved.",
        steps=["Select target and single feature", "Auto-select degree 2-4 by R2",
               "Fit polynomial regression", "Report R2, RMSE, chosen degree",
               "Generate scatter + fitted curve + residual plot"],
        assumptions=["Polynomial relationship", "Approximately normal residuals"],
        libraries_used=["scikit-learn"], min_rows=20,
    ),
    "clustering_kmeans": MethodologyDefinition(
        title="K-Means Clustering", category="Clustering",
        overview="Groups data into K clusters based on feature similarity.",
        when_to_use="Use to find natural segments (customer segments, product groups).",
        steps=["Select numeric features", "Standardize with StandardScaler",
               "Elbow method K=2 to 10", "Fit K-Means with optimal K",
               "Report cluster sizes, silhouette score, centroids",
               "Generate elbow chart + 2D scatter (PCA-reduced)"],
        assumptions=["Spherical clusters", "Similar cluster sizes"],
        libraries_used=["scikit-learn"], min_rows=50,
    ),
    "clustering_dbscan": MethodologyDefinition(
        title="DBSCAN Clustering", category="Clustering",
        overview="Density-based clustering -- finds arbitrary-shape clusters and labels outliers.",
        when_to_use="Use when clusters are not spherical or when outliers matter.",
        steps=["Select numeric features", "Standardize features",
               "Optimize epsilon via k-distance graph", "Fit DBSCAN",
               "Report cluster count, noise points, cluster sizes",
               "Generate 2D scatter with noise highlighted"],
        assumptions=["Density-based clusters present"],
        libraries_used=["scikit-learn"], min_rows=50,
    ),
    "clustering_hierarchical": MethodologyDefinition(
        title="Hierarchical Clustering", category="Clustering",
        overview="Builds a tree of clusters showing how data merges at different scales.",
        when_to_use="Use to visualize the hierarchy of groupings.",
        steps=["Select numeric features", "Standardize features",
               "Compute Ward linkage matrix", "Generate dendrogram + auto cut",
               "Report cluster sizes and within-cluster variance",
               "Generate dendrogram + 2D scatter"],
        assumptions=["Euclidean distance meaningful"],
        libraries_used=["scikit-learn", "scipy.cluster.hierarchy"], min_rows=20,
    ),
    "time_series_arima": MethodologyDefinition(
        title="ARIMA Forecast", category="Time Series",
        overview="Forecasts future values using past patterns.",
        when_to_use="Use when you have a date column and want to predict future values.",
        steps=["Detect date + target columns", "ADF stationarity test",
               "Auto-select ARIMA(p,d,q)", "Fit and forecast 30 periods",
               "Report AIC, RMSE, forecast + confidence intervals",
               "Generate historical + forecast line chart with confidence bands"],
        assumptions=["Stationary after differencing", "No missing dates"],
        libraries_used=["statsmodels"], min_rows=50,
    ),
    "time_series_prophet": MethodologyDefinition(
        title="Prophet Forecast", category="Time Series",
        overview="Forecasting with automatic seasonality detection.",
        when_to_use="Use for business time series with weekly/yearly seasonality.",
        steps=["Detect ds (date) and y (target) columns",
               "Fit Prophet with auto seasonality", "Forecast 90 days",
               "Decompose trend + weekly + yearly seasonality",
               "Generate forecast + component charts"],
        assumptions=["Regular intervals", "At least 2 full seasonal cycles"],
        libraries_used=["prophet"], min_rows=100,
    ),
    "granger_causality": MethodologyDefinition(
        title="Granger Causality", category="Time Series",
        overview="Tests whether one time series helps predict another.",
        when_to_use="Use to test if variable X leads variable Y.",
        steps=["Select two time series columns", "Stationarity test for both",
               "Granger test for lags 1-5", "Report F-stat and p-value per lag",
               "Generate dual line chart + p-value bar chart per lag"],
        assumptions=["Both series stationary", "> 50 time periods"],
        libraries_used=["statsmodels"], min_rows=50,
    ),
    "pca": MethodologyDefinition(
        title="PCA", category="Dimensionality",
        overview="Reduces many numeric columns into uncorrelated components.",
        when_to_use="Use to simplify high-dimensional data or visualize in 2D.",
        steps=["Select numeric columns", "Standardize features",
               "Compute principal components", "Calculate explained variance",
               "Generate scree plot + 2D biplot"],
        assumptions=["Linear relationships", "Numeric features"],
        libraries_used=["scikit-learn"], min_rows=30,
    ),
    "tsne": MethodologyDefinition(
        title="t-SNE", category="Dimensionality",
        overview="Non-linear 2D visualization of high-dimensional data.",
        when_to_use="Use to visualize clusters in complex datasets.",
        steps=["Select numeric columns", "Standardize",
               "Run t-SNE with auto perplexity", "Generate 2D scatter"],
        assumptions=["For visualization only -- distances not directly interpretable"],
        libraries_used=["scikit-learn"], min_rows=50,
    ),
    "umap": MethodologyDefinition(
        title="UMAP", category="Dimensionality",
        overview="Faster alternative to t-SNE preserving global structure.",
        when_to_use="Use for large datasets where t-SNE is too slow.",
        steps=["Select numeric columns", "Standardize",
               "Fit UMAP with auto n_neighbors", "Generate 2D scatter"],
        assumptions=["Numeric features", "More data = better results"],
        libraries_used=["umap-learn"], min_rows=50,
    ),
    "anomaly_isolation_forest": MethodologyDefinition(
        title="Anomaly Detection (Isolation Forest)", category="Anomaly",
        overview="Identifies unusual data points that don't fit normal patterns.",
        when_to_use="Use to find outliers, fraud, or errors.",
        steps=["Select numeric columns", "Fit Isolation Forest (auto contamination)",
               "Score each row", "Report anomaly count + top anomalous rows",
               "Generate scatter with anomalies highlighted + score histogram"],
        assumptions=["Anomalies < 10% of data", "Numeric features"],
        libraries_used=["scikit-learn"], min_rows=50,
    ),
    "anomaly_zscore": MethodologyDefinition(
        title="Anomaly Detection (Z-Score)", category="Anomaly",
        overview="Flags values more than 3 standard deviations from the mean.",
        when_to_use="Use for simple outlier detection on normally-distributed data.",
        steps=["Compute z-score per numeric column",
               "Flag rows with |z| > 3", "Report anomaly count per column",
               "Generate scatter + histogram with threshold lines"],
        assumptions=["Approximately normally distributed data"],
        libraries_used=["scipy.stats"], min_rows=20,
    ),
    "survival_kaplan_meier": MethodologyDefinition(
        title="Kaplan-Meier Survival Analysis", category="Survival",
        overview="Estimates how long until an event occurs.",
        when_to_use="Use with duration + binary event columns (churn, failure, etc.).",
        steps=["Auto-detect duration (numeric) + event (binary) columns",
               "Fit Kaplan-Meier estimator",
               "Log-rank test if group column provided",
               "Report median survival, survival probabilities, at-risk table",
               "Generate survival curve + confidence bands"],
        assumptions=["Independent event times", "Non-informative censoring"],
        libraries_used=["lifelines"], min_rows=30,
    ),
    "market_basket": MethodologyDefinition(
        title="Market Basket Analysis", category="Association",
        overview="Finds items frequently appearing together in transactions.",
        when_to_use="Use with transactional data -- needs transaction ID + item columns.",
        steps=["Detect transaction ID + item columns",
               "Build transaction-item matrix", "Run Apriori (min_support=0.01)",
               "Generate association rules (min_confidence=0.3, min_lift=1.0)",
               "Report top rules by lift", "Generate rules bar chart + network graph"],
        assumptions=["Transactional format data"],
        libraries_used=["mlxtend"], min_rows=100,
    ),
    "pareto": MethodologyDefinition(
        title="Pareto Analysis (80/20)", category="Business",
        overview="Identifies which items contribute 80% of total value.",
        when_to_use="Use to prioritize -- find the few items driving most of the outcome.",
        steps=["Select category + numeric value columns",
               "Sort descending by value", "Compute cumulative percentage",
               "Mark 80% threshold",
               "Report top contributors", "Generate Pareto chart (bar + cumulative line)"],
        assumptions=["Additive numeric metric", "Mutually exclusive categories"],
        libraries_used=["pandas"], min_rows=5,
    ),
    "cohort": MethodologyDefinition(
        title="Cohort Analysis", category="Business",
        overview="Tracks how groups of users behave over time -- measures retention.",
        when_to_use="Use with user ID + acquisition date + activity date.",
        steps=["Detect user ID + acquisition + activity date columns",
               "Assign users to monthly cohorts by first activity",
               "Compute retention rate per cohort per period",
               "Generate retention heatmap + retention curves"],
        assumptions=["Clear user acquisition date", "Parseable dates"],
        libraries_used=["pandas"], min_rows=100,
    ),
    "ai_custom_reasoning": MethodologyDefinition(
        title="AI Custom Reasoning", category="AI Logic",
        overview="Used when standard statistical tests don't apply. AI applies direct logical reasoning to data patterns.",
        when_to_use="Wildcards, fuzzy logic, or complex domain-specific inferences.",
        steps=["Analyze data profile", "Examine representative data sample",
               "Apply internal AI reasoning weights", "Synthesize findings into conversational logic"],
        assumptions=["Data sample is representative", "AI internal knowledge is applicable"],
        libraries_used=["Tenrix AI Reasoning Core"], min_rows=1,
    ),
}
